<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxmnpib\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxmnpib/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSxmnpib.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSxmnpib\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSxmnpib\appDevDebugProjectContainer([
    'container.build_hash' => 'Sxmnpib',
    'container.build_id' => '84244ef8',
    'container.build_time' => 1575798136,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxmnpib');
